site_name: python-for-leetcode
site_description: Python for LeetCode
theme: readthedocs
docs_dir: "."

nav:
  - Home: README.md
  - String: string.md
  - Python Beginner/Intermediate Guide: python-beginner-intermediate-guide.md
  - Data Structure Complexities : data-structure-complexities.md
  - Time Complexity Estimation: time-complexity-estimation.md
  - Special Notes: special-notes.md
  - Concurrency: concurrency.md

plugins:
  - mermaid2:
      version: 11.5.0
  - same-dir
  - search
