site_name: python-for-leetcode
site_description: Python for LeetCode
theme: readthedocs
docs_dir: "."

nav:
  - Home: README.md
  - Python Beginner/Intermediate Guide: python-beginner-intermediate-guide.md
  - Time Complexity Estimation: time-complexity-estimation.md

plugins:
  - mermaid2:
      version: 11.5.0
  - same-dir
  - search
